server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_inventory
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  bootstrap:
    admin:
      enabled: ${ADMIN_BOOTSTRAP_ENABLED:true}
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:}
      email: ${ADMIN_EMAIL:admin@smartinventory.local}
      full-name: ${ADMIN_FULL_NAME:Rendszergazda}