CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       code VARCHAR(50) NOT NULL,
                       name VARCHAR(100) NOT NULL,
                       description TEXT,
                       active BOOLEAN NOT NULL DEFAULT TRUE,
                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT ux_roles_code UNIQUE (code)
);


CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(100) NOT NULL,
                       email VARCHAR(255),
                       password_hash VARCHAR(255) NOT NULL,
                       full_name VARCHAR(150),
                       active BOOLEAN NOT NULL DEFAULT TRUE,
                       failed_login_attempts INTEGER NOT NULL DEFAULT 0,
                       locked_until TIMESTAMPTZ,
                       last_login_at TIMESTAMPTZ,
                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       version BIGINT NOT NULL DEFAULT 0,

                       CONSTRAINT ux_users_username UNIQUE (username),
                       CONSTRAINT ux_users_email UNIQUE (email),
                       CONSTRAINT ck_users_failed_login_attempts
                           CHECK (failed_login_attempts >= 0)
);


CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            assigned_by_user_id BIGINT,

                            CONSTRAINT pk_user_roles
                                PRIMARY KEY (user_id, role_id),

                            CONSTRAINT fk_user_roles_user
                                FOREIGN KEY (user_id)
                                    REFERENCES users(id)
                                    ON DELETE CASCADE,

                            CONSTRAINT fk_user_roles_role
                                FOREIGN KEY (role_id)
                                    REFERENCES roles(id)
                                    ON DELETE CASCADE,

                            CONSTRAINT fk_user_roles_assigned_by
                                FOREIGN KEY (assigned_by_user_id)
                                    REFERENCES users(id)
                                    ON DELETE SET NULL
);


CREATE INDEX ix_user_roles_role_id
    ON user_roles(role_id);


CREATE INDEX ix_users_active
    ON users(active);


INSERT INTO roles (
    code,
    name,
    description
)
VALUES
    (
        'ROLE_ADMIN',
        'Adminisztrátor',
        'Teljes rendszer- és könyvelési jogosultság.'
    ),
    (
        'ROLE_USER',
        'Normál felhasználó',
        'Korlátozott készletmegtekintési és elemzési jogosultság.'
    );