CREATE TABLE vehicles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          vin VARCHAR(17) NOT NULL,
                          vin_short VARCHAR(7) NOT NULL,

                          type_name VARCHAR(255),
                          registration_number VARCHAR(20),

                          acquisition_date DATE,

                          status VARCHAR(30) NOT NULL,
                          vat_type VARCHAR(30) NOT NULL,

                          advertised_price_gross NUMERIC(15, 2),
                          price_source VARCHAR(100),
                          price_updated_at TIMESTAMPTZ,

                          last_seen_at TIMESTAMPTZ,
                          archived_at TIMESTAMPTZ,

                          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          version BIGINT NOT NULL DEFAULT 0,

                          CONSTRAINT ux_vehicles_vin
                              UNIQUE (vin),

                          CONSTRAINT ck_vehicles_vin_length
                              CHECK (char_length(vin) = 17),

                          CONSTRAINT ck_vehicles_vin_short_length
                              CHECK (char_length(vin_short) = 7),

                          CONSTRAINT ck_vehicles_status
                              CHECK (
                                  status IN (
                                             'IMPORTED',
                                             'PENDING_REVIEW',
                                             'IN_PREPARATION',
                                             'AVAILABLE',
                                             'RESERVED',
                                             'SOLD',
                                             'REMOVED',
                                             'ARCHIVED',
                                             'INCOMPLETE'
                                      )
                                  ),

                          CONSTRAINT ck_vehicles_vat_type
                              CHECK (
                                  vat_type IN (
                                               'NORMAL_VAT',
                                               'MARGIN_VAT'
                                      )
                                  ),

                          CONSTRAINT ck_vehicles_advertised_price
                              CHECK (
                                  advertised_price_gross IS NULL
                                      OR advertised_price_gross >= 0
                                  )
);


CREATE INDEX ix_vehicles_vin_short
    ON vehicles(vin_short);

CREATE INDEX ix_vehicles_status
    ON vehicles(status);

CREATE INDEX ix_vehicles_registration_number
    ON vehicles(registration_number);