ALTER TABLE vehicles
    ADD COLUMN brand VARCHAR(100),
    ADD COLUMN vehicle_condition VARCHAR(20);

ALTER TABLE vehicles
    ADD CONSTRAINT ck_vehicles_condition
        CHECK (
            vehicle_condition IS NULL
                OR vehicle_condition IN ('NEW', 'USED')
            );


CREATE TABLE import_batches (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                import_type VARCHAR(30) NOT NULL,
                                original_filename VARCHAR(255) NOT NULL,
                                file_hash VARCHAR(64) NOT NULL,

                                imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                total_rows INTEGER NOT NULL DEFAULT 0,
                                inserted_rows INTEGER NOT NULL DEFAULT 0,
                                skipped_rows INTEGER NOT NULL DEFAULT 0,
                                rejected_rows INTEGER NOT NULL DEFAULT 0,

                                CONSTRAINT ux_import_batches_type_file_hash
                                    UNIQUE (import_type, file_hash),

                                CONSTRAINT ck_import_batches_type
                                    CHECK (
                                        import_type IN (
                                                        'VEHICLE',
                                                        'INTEREST',
                                                        'COMPANY_CAR_TAX'
                                            )
                                        ),

                                CONSTRAINT ck_import_batches_row_counts
                                    CHECK (
                                        total_rows >= 0
                                            AND inserted_rows >= 0
                                            AND skipped_rows >= 0
                                            AND rejected_rows >= 0
                                        )
);


CREATE TABLE vehicle_cost_entries (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                      vehicle_id BIGINT NOT NULL,
                                      import_batch_id BIGINT,

                                      cost_type VARCHAR(30) NOT NULL,

                                      accounting_date DATE NOT NULL,
                                      document_number VARCHAR(100),
                                      supplier_name VARCHAR(255),
                                      external_document_number VARCHAR(100),

                                      amount NUMERIC(15, 2) NOT NULL,

                                      source_row_number INTEGER,
                                      source_fingerprint VARCHAR(64) NOT NULL,

                                      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                      CONSTRAINT fk_vehicle_cost_entries_vehicle
                                          FOREIGN KEY (vehicle_id)
                                              REFERENCES vehicles(id)
                                              ON DELETE CASCADE,

                                      CONSTRAINT fk_vehicle_cost_entries_import_batch
                                          FOREIGN KEY (import_batch_id)
                                              REFERENCES import_batches(id)
                                              ON DELETE SET NULL,

                                      CONSTRAINT ux_vehicle_cost_entries_fingerprint
                                          UNIQUE (source_fingerprint),

                                      CONSTRAINT ck_vehicle_cost_entries_type
                                          CHECK (
                                              cost_type IN (
                                                            'ACQUISITION',
                                                            'INTEREST',
                                                            'COMPANY_CAR_TAX',
                                                            'OTHER'
                                                  )
                                              )
);


CREATE INDEX ix_vehicle_cost_entries_vehicle_id
    ON vehicle_cost_entries(vehicle_id);

CREATE INDEX ix_vehicle_cost_entries_cost_type
    ON vehicle_cost_entries(cost_type);

CREATE INDEX ix_vehicle_cost_entries_accounting_date
    ON vehicle_cost_entries(accounting_date);

CREATE INDEX ix_import_batches_imported_at
    ON import_batches(imported_at);