CREATE TABLE import_row_errors (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   import_batch_id BIGINT NOT NULL,

                                   source_row_number INTEGER NOT NULL,

                                   error_message VARCHAR(1000) NOT NULL,

                                   created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   CONSTRAINT fk_import_row_errors_import_batch
                                       FOREIGN KEY (import_batch_id)
                                           REFERENCES import_batches(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT ck_import_row_errors_source_row
                                       CHECK (source_row_number > 0)
);

CREATE INDEX ix_import_row_errors_import_batch_id
    ON import_row_errors(import_batch_id);